#!/usr/bin/env perl
use strict;
use warnings;

print "# Autogenerated by tools/vectors.pl                                  \n";
print "# Do not edit; do not track in version control                       \n";
print "        .intel_syntax noprefix                                       \n";
print "        .section .text                                               \n";
print "        .global vectors                                              \n";
print "        .align  16                                                   \n";
print "vectors:                                                             \n";

for my $vec (0..255) {
    print "_int$vec:                                                        \n";
    print "        push    $vec                                             \n";
    print "        jmp     istub                                            \n";
}
