#!/usr/bin/env perl
use strict;
use warnings;

print "# Autogenerated by tools/vectors.pl                                  \n";
print "# Do not edit; do not track in version control                       \n";
print "        .intel_syntax noprefix                                       \n";
print "        .section .text                                               \n";
print "        .section .data                                               \n";
print "        .global vectors                                              \n";
print "vectors:                                                             \n";
for my $vec (0..255) {
    print "        .quad   _int$vec                                         \n";
}

print "        .section .text                                               \n";
my %has_error_code = map { $_ => 1 } (8, 10, 11, 12, 13, 14, 17, 21, 29, 30);

for my $vec (0..255) {
    print "_int$vec:                                                        \n";

    if (!exists($has_error_code{$vec})) {
        print "        push    0                                            \n";
    }

    print "        push    $vec                                             \n";
    print "        jmp     istub                                            \n";
}
